spring:
  application:
    name: "Blue Velvet"
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL:jdbc:mysql://localhost:3306/bluevelvet}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    filter:
      order: 5
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${SERVER_PORT:8082}

# Configurações personalizadas
app:
  upload:
    dir: ${UPLOAD_DIR:src/main/resources/static/uploads}
  admin:
    username: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}

logging:
  level:
    org.springframework.security: INFO
